### ISSUE TITLE
Julia kernel error

### ISSUE THREAD

**Issue by MKLu-DE** [orchest-examples/julia-orchest-sdk#1]
Initializeing Julia Kernel, get "Error Starting Kernel - Invalid response: 504 ".

**Comment by ricklamers** [comment]
Thanks for reporting. I'll look into this to see if I can reproduce.

Can you share some details about your setup? Operating system? Orchest version?

**Comment by MKLu-DE** [comment]
Thanks for the light-speed response!!!
PC: win 10
Orchest version: 2 vCPUs, 8 GiB, free version, v2021.12.3
Environments: python and julia.

**Comment by ricklamers** [comment]
I think it was due to a missing shebang. Thanks for spotting this. The CI/CD for the v2022.01.0 release is currently running. It should be on Docker Hub and ready for update (`./orchest update`) within 20 minutes.

https://github.com/orchest/orchest/pull/629/commits/89aed05e6dacf47856a73c93b0b5064effe4df6c

**Comment by MKLu-DE** [comment]
Hi Ricklamer, thanks a lot. That is cool!!!

Solution:
- go to "**setting**"
- **update** your orchest to latest version
- **restart** your pipeline & jupyterlab
